version: '3.8'
services:

    patient-database:
        image: mysql:5.7
        container_name: patient-database
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: patientDatabase
        volumes:
            - db_data:/var/lib/mysql
        ports: 
            - 3307:3306


    notes-database:
        image: mongo:4
        container_name: notes-database
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
      
    patient-api:
        image: patient-api:latest
        container_name: patient-api
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://patient-database:3306/patientDatabase
        build:
            context: PatientApiService
            dockerfile: Dockerfile
        depends_on:
            - patient-database
        restart: on-failure
        ports: 
            - 8081:8081
            
    notes-patient:
        image: notes-patient:latest
        container_name: notes-patient
        environment:
            - spring_data_mongodb_host=notes-database
        build:
            context: NotesPatientService
            dockerfile: Dockerfile
        depends_on:
            - notes-database
        restart: on-failure
        ports:
            - 8082:8082

    patient-assessment:
        image: patient-assessment:latest
        container_name: patient-assessment
        build:
            context: PatientAssessmentService
            dockerfile: Dockerfile
        depends_on:
            - patient-api
            - notes-database
        restart: on-failure
        ports:
            - 8083:8083
            
    user-interface:
        image: user-interface:latest
        container_name: user-interface
        build:
            context: UserInterfaceWebService
            dockerfile: Dockerfile
        depends_on:
            - patient-api
            - notes-patient
            - patient-assessment
        restart: on-failure
        ports: 
            - 8080:8080
    
volumes:
    db_data: {}
    mongodb_data_container: {}